# Generated by Django 4.1.4 on 2022-12-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0004_alter_farm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='farm',
            name='produce',
            field=models.CharField(max_length=500),
        ),
    ]
